### ISSUE TITLE
Example sketch does not compile

### ISSUE THREAD

**Issue by ReiniervdL** [LinkLabs/linklabs-arduino#1]
Arduino: 1.6.5 (Mac OS X), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

Fixed file name, space in file name is not allowed.

After that, the sketch does not compile:

analog_reporting.ino: In function 'void setup()':
analog_reporting:36: error: 'll_config_set' was not declared in this scope
analog_reporting:41: error: 'll_irq_flags' was not declared in this scope
analog_reporting:46: error: 'll_irq_flags' was not declared in this scope
analog_reporting.ino: In function 'void loop()':
analog_reporting:65: error: 'll_irq_flags' was not declared in this scope
analog_reporting:69: error: 'll_packet_send_ack' was not declared in this scope
'll_config_set' was not declared in this scope

**Comment by swohlerLL** [comment]
This compiled successfully by creating the following directory structure:
[Arduino 1.6.7 Windows 10]

```
linklabs-arduino/examples/analog_reporting/analog_reporting.ino
```

And by moving the SymphonyLink.[ch] files into:

```
/Program Files (x86)/Arduino/libraries/SymphonyLink/
```

The errors indicated on your system seem to indicate that the IDE can't locate the SymphonyLink library.

**Comment by ReiniervdL** [comment]
Hi,

I tried install on a Windows 7 machine. No luck.
See error report here:

Arduino: 1.6.5 (Windows 7), Board: "Arduino/Genuino Uno"

In file included from analog_reporting.ino:1:0:
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:78:5: error: 'uint32_t' does not name a type
    uint32_t network_id_node;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:79:5: error: 'uint32_t' does not name a type
    uint32_t network_id_gw;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:80:5: error: 'int8_t' does not name a type
    int8_t gateway_channel;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:81:5: error: 'uint32_t' does not name a type
    uint32_t gateway_frequency;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:82:5: error: 'uint32_t' does not name a type
    uint32_t last_rx_tick;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:83:5: error: 'int16_t' does not name a type
    int16_t rssi;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:84:5: error: 'uint8_t' does not name a type
    uint8_t snr;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:86:5: error: 'uint8_t' does not name a type
    uint8_t is_scanning_gateways;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:87:5: error: 'uint64_t' does not name a type
    uint64_t gateway_id;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:92:5: error: 'uint32_t' does not name a type
    uint32_t band_edge_lower;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:93:5: error: 'uint32_t' does not name a type
    uint32_t band_edge_upper;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:94:5: error: 'uint32_t' does not name a type
    uint32_t band_edge_guard;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:95:5: error: 'uint8_t' does not name a type
    uint8_t chan_step_size;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:96:5: error: 'uint8_t' does not name a type
    uint8_t chan_step_offset;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:100:5: error: 'uint32_t' does not name a type
    uint32_t num_send_calls;            // Number of times SendMessage has been called successfully
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:101:5: error: 'uint32_t' does not name a type
    uint32_t num_pkts_transmitted;      // Number of packet transmissions (includes retries)
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:102:5: error: 'uint32_t' does not name a type
    uint32_t num_gateway_scans;         // Number of gateway scans
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:103:5: error: 'uint32_t' does not name a type
    uint32_t num_collisions;            // Number of CSMA collisions detected
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:104:5: error: 'uint32_t' does not name a type
    uint32_t num_ack_successes;         // Number of successful acknowledgments
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:105:5: error: 'uint32_t' does not name a type
    uint32_t num_ack_failures;          // Number of failed acknowledgments
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:106:5: error: 'uint32_t' does not name a type
    uint32_t num_sync_failures;         // Number of Sync failures
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:107:5: error: 'uint32_t' does not name a type
    uint32_t num_canceled_pkts_ack;     // Number of times packet was canceled due to LLABS_ACK_FAIL_RETRIES
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:108:5: error: 'uint32_t' does not name a type
    uint32_t num_canceled_pkts_csma;    // Number of times packet was canceled due to LLABS_MAX_CSMA_COLLISIONS
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:109:5: error: 'uint32_t' does not name a type
    uint32_t num_rx_errors;             // Number of times we received a Rx error from the back end
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:207:5: error: 'uint16_t' does not name a type
    uint16_t cpu_code;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:208:5: error: 'uint16_t' does not name a type
    uint16_t functionality_code;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:212:5: error: 'uint8_t' does not name a type
    uint8_t major;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:213:5: error: 'uint8_t' does not name a type
    uint8_t minor;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:214:5: error: 'uint16_t' does not name a type
    uint16_t tag;
    ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:250:1: error: 'uint8_t' does not name a type
uint8_t read_uint8(const uint8_t buff[], size_t \* index);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:251:1: error: 'uint16_t' does not name a type
uint16_t read_uint16(const uint8_t buff[], size_t \* index);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:252:1: error: 'uint32_t' does not name a type
uint32_t read_uint32(const uint8_t buff[], size_t \* index);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:253:1: error: 'uint64_t' does not name a type
uint64_t read_uint64(const uint8_t buff[], size_t _index);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:254:18: error: variable or field 'write_uint8' declared void
void write_uint8(uint8_t x, uint8_t *_buff);
                 ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:254:18: error: 'uint8_t' was not declared in this scope
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:254:29: error: 'uint8_t' was not declared in this scope
void write_uint8(uint8_t x, uint8_t *_buff);
                            ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:254:39: error: 'buff' was not declared in this scope
void write_uint8(uint8_t x, uint8_t *_buff);
                                      ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:255:19: error: variable or field 'write_uint16' declared void
void write_uint16(uint16_t x, uint8_t *_buff);
                  ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:255:19: error: 'uint16_t' was not declared in this scope
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:255:31: error: 'uint8_t' was not declared in this scope
void write_uint16(uint16_t x, uint8_t *_buff);
                              ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:255:41: error: 'buff' was not declared in this scope
void write_uint16(uint16_t x, uint8_t *_buff);
                                        ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:256:19: error: variable or field 'write_uint32' declared void
void write_uint32(uint32_t x, uint8_t *_buff);
                  ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:256:19: error: 'uint32_t' was not declared in this scope
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:256:31: error: 'uint8_t' was not declared in this scope
void write_uint32(uint32_t x, uint8_t *_buff);
                              ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:256:41: error: 'buff' was not declared in this scope
void write_uint32(uint32_t x, uint8_t *_buff);
                                        ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:257:19: error: variable or field 'write_uint64' declared void
void write_uint64(uint64_t x, uint8_t *_buff);
                  ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:257:19: error: 'uint64_t' was not declared in this scope
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:257:31: error: 'uint8_t' was not declared in this scope
void write_uint64(uint64_t x, uint8_t *_buff);
                              ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:257:41: error: 'buff' was not declared in this scope
void write_uint64(uint64_t x, uint8_t **buff);
                                        ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:258:36: error: 'uint8_t' does not name a type
void ll_net_info_deserialize(const uint8_t buff[NET_INFO_BUFF_SIZE], llabs_network_info_t *net_info);
                                   ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:258:67: error: ISO C++ forbids declaration of 'buff' with no type [-fpermissive]
void ll_net_info_deserialize(const uint8_t buff[NET_INFO_BUFF_SIZE], llabs_network_info_t *net_info);
                                                                  ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:259:1: error: 'uint16_t' does not name a type
uint16_t ll_net_info_serialize(const llabs_network_info_t *net_info, uint8_t buff[NET_INFO_BUFF_SIZE]);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:260:39: error: 'uint8_t' does not name a type
void ll_dl_band_cfg_deserialize(const uint8_t buff[DL_BAND_CFG_SIZE], llabs_dl_band_cfg_t *dl_cfg);
                                      ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:260:68: error: ISO C++ forbids declaration of 'buff' with no type [-fpermissive]
void ll_dl_band_cfg_deserialize(const uint8_t buff[DL_BAND_CFG_SIZE], llabs_dl_band_cfg_t *dl_cfg);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:261:1: error: 'uint16_t' does not name a type
uint16_t ll_dl_band_cfg_serialize(const llabs_dl_band_cfg_t *dl_cfg, uint8_t buff[DL_BAND_CFG_SIZE]);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:262:33: error: 'uint8_t' does not name a type
void ll_stats_deserialize(const uint8_t buff[STATS_SIZE], llabs_stats_t *stats);
                                ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:262:56: error: ISO C++ forbids declaration of 'buff' with no type [-fpermissive]
void ll_stats_deserialize(const uint8_t buff[STATS_SIZE], llabs_stats_t *stats);
                                                       ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:263:1: error: 'uint16_t' does not name a type
uint16_t ll_stats_serialize(const llabs_stats_t *stats, uint8_t buff[STATS_SIZE]);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:264:1: error: 'int32_t' does not name a type
int32_t transport_write(uint8_t *buff, uint16_t len);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:265:1: error: 'int32_t' does not name a type
int32_t transport_read(uint8_t *buff, uint16_t len);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:266:1: error: 'uint16_t' does not name a type
uint16_t compute_checksum(uint8_t *hdr, uint16_t hdr_len, uint8_t *payload, uint16_t payload_len);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:267:1: error: 'int32_t' does not name a type
int32_t recv_packet(opcode_t op, uint8_t message_num, uint8_t *buf, uint16_t len);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:268:31: error: 'uint8_t' has not been declared
void send_packet(opcode_t op, uint8_t message_num, uint8_t *buf, uint16_t len);
                              ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:268:52: error: 'uint8_t' has not been declared
void send_packet(opcode_t op, uint8_t message_num, uint8_t *buf, uint16_t len);
                                                   ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:268:66: error: 'uint16_t' has not been declared
void send_packet(opcode_t op, uint8_t message_num, uint8_t *buf, uint16_t len);
                                                                 ^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:269:1: error: 'int32_t' does not name a type
int32_t hal_read_write(opcode_t op, uint8_t buf_in[], uint16_t in_len, uint8_t buf_out[], uint16_t out_len);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:270:1: error: 'int32_t' does not name a type
int32_t ll_packet_recv(uint16_t num_timeout_symbols, uint8_t buf[], uint16_t len, uint8_t *bytes_received);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:271:1: error: 'int32_t' does not name a type
int32_t ll_packet_recv_with_rssi(uint16_t num_timeout_symbols, uint8_t buf[], uint16_t len, uint8_t *bytes_received);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:272:1: error: 'int32_t' does not name a type
int32_t ll_retrieve_message(uint8_t *buf, uint8_t *size, int16_t *rssi, uint8_t *snr);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:273:1: error: 'int32_t' does not name a type
int32_t ll_packet_send_queue(uint8_t buf[], uint16_t len);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:274:1: error: 'int32_t' does not name a type
int32_t ll_packet_send(uint8_t buf[], uint16_t len);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:275:1: error: 'int32_t' does not name a type
int32_t ll_firmware_type_get(ll_firmware_type_t *t);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:276:1: error: 'int32_t' does not name a type
int32_t ll_hardware_type_get(ll_hardware_type_t *t);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:277:1: error: 'int32_t' does not name a type
int32_t ll_interface_version_get(ll_version_t *version);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:278:1: error: 'int32_t' does not name a type
int32_t ll_version_get(ll_version_t *version);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:279:1: error: 'int32_t' does not name a type
int32_t ll_sleep_block(void);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:280:1: error: 'int32_t' does not name a type
int32_t ll_sleep_unblock(void);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:281:1: error: 'int32_t' does not name a type
int32_t ll_receive_mode_set(uint8_t rx_mode);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:282:1: error: 'int32_t' does not name a type
int32_t ll_receive_mode_get(uint8_t *rx_mode);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:283:1: error: 'int32_t' does not name a type
int32_t ll_mailbox_request(void);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:284:1: error: 'int32_t' does not name a type
int32_t ll_qos_request(uint8_t qos);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:285:1: error: 'int32_t' does not name a type
int32_t ll_qos_get(uint8_t *qos);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:286:1: error: 'int32_t' does not name a type
int32_t ll_app_token_set(const uint8_t *app_token, uint8_t len);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:287:1: error: 'int32_t' does not name a type
int32_t ll_app_token_get(uint8_t *app_token);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:288:1: error: 'int32_t' does not name a type
int32_t ll_app_reg_get(uint8_t *is_registered);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:289:1: error: 'int32_t' does not name a type
int32_t ll_encryption_key_exchange_request(void);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:290:1: error: 'int32_t' does not name a type
int32_t ll_get_state(enum ll_state *state, enum ll_tx_state *tx_state, enum ll_rx_state *rx_state);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:291:1: error: 'int32_t' does not name a type
int32_t ll_mac_mode_set(ll_mac_type_t mac_mode);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:292:1: error: 'int32_t' does not name a type
int32_t ll_mac_mode_get(ll_mac_type_t *mac_mode);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:293:1: error: 'int32_t' does not name a type
int32_t ll_antenna_set(uint8_t ant);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:294:1: error: 'int32_t' does not name a type
int32_t ll_antenna_get(uint8_t *ant);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:295:1: error: 'int32_t' does not name a type
int32_t ll_net_token_get(uint32_t *p_net_token);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:296:1: error: 'int32_t' does not name a type
int32_t ll_net_token_set(uint32_t net_token);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:297:1: error: 'int32_t' does not name a type
int32_t ll_config_get(uint32_t *net_token, uint8_t app_token[APP_TOKEN_LEN], enum ll_downlink_mode *dl_mode, uint8_t *qos);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:298:1: error: 'int32_t' does not name a type
int32_t ll_net_info_get(llabs_network_info_t *p_net_info);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:299:1: error: 'int32_t' does not name a type
int32_t ll_stats_get(llabs_stats_t *s);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:300:1: error: 'int32_t' does not name a type
int32_t ll_dl_band_cfg_get(llabs_dl_band_cfg_t *p);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:301:1: error: 'int32_t' does not name a type
int32_t ll_dl_band_cfg_set(const llabs_dl_band_cfg_t *p);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:302:1: error: 'int32_t' does not name a type
int32_t ll_config_set(uint32_t net_token, const uint8_t app_token[APP_TOKEN_LEN], enum ll_downlink_mode dl_mode, uint8_t qos);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:303:1: error: 'int32_t' does not name a type
int32_t ll_rssi_scan_set(uint32_t u1, uint32_t u2, uint32_t u3, uint32_t u4);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:304:1: error: 'int32_t' does not name a type
int32_t ll_rssi_scan_get(uint8_t buf[], uint16_t len, uint8_t *bytes_received);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:305:1: error: 'int32_t' does not name a type
int32_t ll_unique_id_get(uint64_t *unique_id);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:307:1: error: 'int32_t' does not name a type
int32_t ll_radio_params_get(uint8_t *sf, uint8_t *cr, uint8_t *bw, uint32_t *freq, uint16_t *preamble_syms, uint8_t *header_enabled, uint8_t *crc_enabled, uint8_t *iq_inverted);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:308:1: error: 'int32_t' does not name a type
int32_t ll_radio_params_set(uint8_t flags, uint8_t sf, uint8_t cr, uint8_t bw, uint32_t freq,
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:311:1: error: 'int32_t' does not name a type
int32_t ll_bandwidth_set(uint8_t bandwidth);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:312:1: error: 'int32_t' does not name a type
int32_t ll_spreading_factor_set(uint8_t sf);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:313:1: error: 'int32_t' does not name a type
int32_t ll_coding_rate_set(uint8_t coding_rate);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:314:1: error: 'int32_t' does not name a type
int32_t ll_tx_power_set(int8_t pwr);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:315:1: error: 'int32_t' does not name a type
int32_t ll_tx_power_get(int8_t *pwr);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:316:1: error: 'int32_t' does not name a type
int32_t ll_frequency_set(uint32_t freq);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:317:1: error: 'int32_t' does not name a type
int32_t ll_preamble_syms_set(uint16_t num_syms);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:318:1: error: 'int32_t' does not name a type
int32_t ll_header_enabled_set(uint8_t enabled);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:320:1: error: 'int32_t' does not name a type
int32_t ll_crc_enabled_set(uint8_t enabled);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:321:1: error: 'int32_t' does not name a type
int32_t ll_iq_inversion_set(uint8_t inverted);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:322:1: error: 'int32_t' does not name a type
int32_t ll_sync_word_set(uint8_t sync_word);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:323:1: error: 'int32_t' does not name a type
int32_t ll_sync_word_get(uint8_t *sync_word);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:324:1: error: 'int32_t' does not name a type
int32_t ll_settings_store(void);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:325:1: error: 'int32_t' does not name a type
int32_t ll_settings_delete(void);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:326:1: error: 'int32_t' does not name a type
int32_t ll_restore_defaults(void);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:327:1: error: 'int32_t' does not name a type
int32_t ll_sleep(void);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:328:1: error: 'int32_t' does not name a type
int32_t ll_reset_mcu(void);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:329:1: error: 'int32_t' does not name a type
int32_t ll_bootloader_mode(void);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:330:1: error: 'int32_t' does not name a type
int32_t ll_echo_mode();
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:331:1: error: 'int32_t' does not name a type
int32_t ll_packet_recv_cont(uint8_t buf[], uint16_t len, uint8_t *bytes_received);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:332:1: error: 'int32_t' does not name a type
int32_t ll_irq_flags(uint32_t flags_to_clear, uint32_t *flags);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:333:1: error: 'int32_t' does not name a type
int32_t ll_packet_send_ack(uint8_t buf[], uint16_t len);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:334:1: error: 'int32_t' does not name a type
int32_t ll_packet_send_unack(uint8_t buf[], uint16_t len);
^
C:\Users\Family\Documents\Arduino\libraries\linklabs-arduino-master/SymphonyLink.h:335:1: error: 'int32_t' does not name a type
int32_t ll_transmit_cw(void);
^
analog_reporting.ino: In function 'void setup()':
analog_reporting:26: error: 'Serial1' was not declared in this scope
analog_reporting:36: error: 'll_config_set' was not declared in this scope
analog_reporting:41: error: 'll_irq_flags' was not declared in this scope
analog_reporting:46: error: 'll_irq_flags' was not declared in this scope
analog_reporting.ino: In function 'void loop()':
analog_reporting:65: error: 'll_irq_flags' was not declared in this scope
analog_reporting:69: error: 'll_packet_send_ack' was not declared in this scope
'Serial1' was not declared in this scope

 This report would have more information with
 "Show verbose output during compilation"
 enabled in File > Preferences.

**Comment by swohlerLL** [comment]
I replicated this by using 1.6.5 on a Win7 machine. This is because the arduino.h header include statement was in the .cpp file instead of the .h file.

That issue should be resolved now. Also, if you try to compile with the board set to Arduino Uno, it will fail because it uses Serial1. You will have to change the board type to Arduino Mega2560.

**Comment by ReiniervdL** [comment]
Hi,

Thanks for the quick response. If you’re working today, so am i :-)
The latest change solved the issue with the library.
The Arduino IDE (on Mac OSX) was able to compile and upload to the Arduino Mega.

Now I am trying to figure out how to use this example when having 2 modules.
I connected one module dev board to a PC running Symphony app, the other dev board runs the Arduino sketch on an Arduino Mega.
On the PC app I can see both modules attached, but no receive data.

My intent is to use the two LL-RLP-20’s as point-to-point transparent data link serial in/serial out.
Is there an Arduino example to accomplish this?

Kind regards,

Reinier van der Lee
